site_name: OPIL
site_url: https://opil-documentation.readthedocs.org
repo_url: https://github.com/opil/documentation.git
site_description: OPIL Documentation
site_author: OPIL Team
docs_dir: docs
site_dir: html

markdown_extensions:
    - toc:
        baselevel: 3
    - fenced_code

use_directory_urls: false

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        - bash
        - yml
pages:
    - Home: index.md
    - Getting Started: 
        - Introduction to OPIL architecture: start/index.md
        - Deployment: start/deployment.md
    - Showcases:
        - Introduction: showcases/index.md 
        - Chemi: showcases/chemi.md
        - Engino: showcases/engino.md
        - Muraplast: showcases/muraplast.md
    - Administrator's Guide: 
#        - Introduction: admin/index.md
        - Installation:
            - OPIL Networking: admin/OPIL/opil_networking.md
            - OPIL Server: admin/OPIL/opil_server.md
            - OPIL Server Nodes:
                - Task Planner: 
                    - Installation: admin/TP/opil_server_tp_install.md
                    - Getting started: admin/TP/opil_server_tp_gettingStarted.md
                    - Deinstallation: admin/TP/opil_server_tp_deinstall.md
                    - Upgrades: admin/TP/opil_server_tp_upgrade.md
                    - Deprecated: admin/TP/opil_server_tp_deprecated.md 
                - Human Machine Interface: 
                    - Installation: admin/HMI/opil_server_hmi_install.md
#                    - Getting started: admin/HMI/opil_server_hmi_gettingStarted.md
#                    - Deinstallation: admin/HMI/opil_server_hmi_deinstall.md
                    - Upgrades: admin/HMI/opil_server_hmi_upgrades.md
                    - Deprecated: admin/HMI/opil_server_hmi_deprecated.md
                - Sensing and Perception - Central SP:
                    - Installation: admin/SP/opil_server_sp_install.md
                    - Getting started: admin/SP/opil_server_sp_gettingStarted.md
                    - Deinstallation: admin/SP/opil_server_sp_deinstall.md
                    - Upgrades: admin/SP/opil_server_sp_upgrades.md
                    - Deprecated: admin/SP/opil_server_sp_deprecated.md                
            - OPIL IoT Nodes:
#                - Introduction: admin/opil_iot.md
                - RAN: 
                    - Introduction: admin/RAN/opil_iot_ran.md
                    - Installation: admin/RAN/opil_server_ran_install.md
                    - Getting started: admin/RAN/opil_server_ran_gettingStarted.md
                    - Deinstallation: admin/RAN/opil_server_ran_deinstallation.md
                    - Upgrades: admin/RAN/opil_server_ran_upgrades.md
                    - Deprecated: admin/RAN/opil_server_ran_deprecated.md 
                - SAN: 
                    - Introduction: admin/SAN/opil_iot_san.md
                    - Installation: admin/SAN/opil_server_san_install.md
                    - Getting started:
                        - Before configureing SAN: admin/SAN/SAN_start.md
                        - Using Docker: admin/SAN/SAN_docker_files.md
                        - Configuration File: admin/SAN/SAN_run.md
                        - Introduction to Drivers: admin/SAN/SAN_drivers.md
                        - Example: admin/SAN/SAN_example.md
                    - Deinstallation: admin/SAN/opil_server_san_deinstallation.md
                    - Upgrades: admin/SAN/opil_server_san_upgrades.md
                    - Deprecated: admin/SAN/opil_server_san_deprecated.md
                - Sensing and Perception - Local SP:
                    - Introduction: admin/SP/opil_local_SP.md
                    - Installation: admin/SP/opil_local_sp_install.md
                    - Getting started: admin/SP/opil_local_sp_gettingStarted.md
                    - Deinstallation: admin/SP/opil_local_sp_deinstall.md
                    - Upgrades: admin/SP/opil_local_sp_upgrades.md
                    - Deprecated: admin/SP/opil_local_sp_deprecated.md                
#                - HAN: 
#                    - Introduction: admin/HAN/opil_iot_han.md
#                    - Installation: admin/HAN/opil_server_han_install.md
#                    - Getting started: admin/HAN/opil_server_han_gettingStarted.md
#                    - Deinstallation: admin/HAN/opil_server_han_deinstallation.md
#                    - Upgrades: admin/HAN/opil_server_han_upgrades.md
#                    - Deprecated: admin/HAN/opil_server_han_deprecated.md
            - Opil VC Nodes:
                - Deployment: admin/opil_vc.md
                - RAN VC: 
                    - Introduction: admin/RANVC/opil_vc_ran.md
                    - Installation: admin/RANVC/opil_server_ranvc_install.md
                    - Getting started: admin/RANVC/opil_server_ranvc_gettingStarted.md
                    - Deinstallation: admin/RANVC/opil_server_ranvc_deinstallation.md
                    - Upgrades: admin/RANVC/opil_server_ranvc_upgrades.md
                    - Deprecated: admin/RANVC/opil_server_ranvc_deprecated.md
                - SAN VC: 
                    - Introduction: admin/SANVC/opil_vc_sanvc.md
                    - Getting started: admin/SANVC/opil_server_sanvc_gettingStarted.md
                    - Installation: admin/SANVC/opil_server_sanvc_install.md
                    - Deinstallation: admin/SANVC/opil_server_sanvc_deinstallation.md
                    - Upgrades: admin/SANVC/opil_server_sanvc_upgrades.md
                    - Deprecated: admin/SANVC/opil_server_sanvc_deprecated.md
                - SAN VC Actuator: 
                    - Introduction: admin/SANVCACT/opil_vc_sanvcact.md
                    - Installation: admin/SANVCACT/opil_server_sanvcact_install.md
                    - Getting started: admin/SANVCACT/opil_server_sanvcact_gettingStarted.md
                    - Deinstallation: admin/SANVCACT/opil_server_sanvcact_deinstallation.md
                    - Upgrades: admin/SANVCACT/opil_server_sanvcact_upgrades.md
                    - Deprecated: admin/SANVCACT/opil_server_sanvcact_deprecated.md
        - Modules Description:
            - Introduction: admin/OPIL/opil_desc_intro.md
            - OPIL Server Nodes:                              
                - Task Planner: admin/TP/opil_desc_tp_intro.md
                - Human Machine Interface: admin/HMI/opil_desc_HMI_intro.md
                - Sensing & Perception - Central SP: admin/SP/opil_desc_SP_intro.md         
                - Human Machine Interaction: admin/HMI/opil_desc_HMI_intro.md   
            - OPIL IoT Nodes:
                - Introduction: admin/opil_desc_node_intro.md
                - RAN: admin/RAN/opil_desc_ran.md
                - SAN: admin/SAN/opil_desc_san.md
                - Sensing & Perception - Local SP: admin/SP/opil_desc_local_SP_intro.md            
#               - HAN: admin/HAN/opil_desc_han.md
            - OPIL VC Nodes:
                - Introduction: admin/opil_desc_vc_node_intro.md
                - VC RAN: admin/RANVC/opil_desc_vc_ran.md
                - VC SAN: admin/SANVC/opil_desc_vc_san.md
                - VC SAN Actuator: admin/SANVCACT/opil_desc_vc_sanvcact.md
    - Developer's Guide:
        - Introduction: develop/index.md
        - Technology Guidelines: develop/technology_guidelines.md
        - Programming Guidelines: develop/technology_programming.md 
        - API Documentation:
            - OPIL Server Nodes:
                - Task Planner:
                    - Introduction to API: develop/TP/opil_tp_API_intro.md
                    - Business Process Optimization:  develop/TP/opil_config_tp_bpo.md
                    - Motion Path Planning: develop/TP/opil_config_tp_mpp.md
                    - Task Supervisor: develop/TP/opil_config_tp_tasksupervisor.md
                    - API: develop/TP/opil_tp_api.md
                    - Interfaces: develop/TP/opil_tp_interfaces.md
                - Human Machine Interface: 
                    - API: develop/HMI/opil_api_hmi.md
                    - Interfaces: develop/HMI/opil_interfaces_hmi.md
                - Sensing & Perception - Central SP: 
                    - API: develop/SP/opil_api_sp.md
                    - Interfaces: develop/SP/opil_sp_interfaces.md
            - OPIL IoT Nodes:
                - Robot Agent Node (RAN): 
                    - API: develop/RAN/opil_api_ran.md
                    - Interfaces: develop/RAN/opil_interfaces_ran.md
                    - Introduction: develop/RAN/opil_introd_ran.md
                - Sensor Agent Node (SAN): 
                    - API: develop/SAN/opil_api_san.md
                    - Docker files: docs/develop/SAN/opil_docker_san.md 
                    - Drivers: develop/SAN/opil_drivers_san.md
                    - Configuration File: develop/SAN/opil_run_san.md
                - Sensing & Perception - Local SP: 
                    - API: develop/SP/opil_api_local_sp.md
                    - Interfaces: develop/SP/opil_local_sp_interfaces.md
#                - Human Agent Node (HAN):
#                    - API: develop/HAN/opil_api_han.md
            - OPIL VC Nodes:
                - VC RAN: develop/RANVC/opil_api_vc_ran.md
                - VC SAN: develop/SANVC/opil_api_vc_san.md
                - VC SAN Actuator: develop/SANVCACT/opil_api_vc_sanvcact.md
            - Examples: develop/examples.md
theme: readthedocs
plugins:
    - search
