site_name: OPIL
site_url: https://opil-documentation.readthedocs.org
repo_url: https://github.com/opil/documentation.git
site_description: OPIL Documentation
docs_dir: docs
site_dir: html

markdown_extensions:
    - toc:
        baselevel: 3
    - fenced_code

use_directory_urls: false

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        
nav:
    - Home: index.md
    - Getting Started: 
        - Introduction to OPIL: start/index.md
        - Deployment: start/deployment.md
        
theme: readthedocs
plugins:
    - search
