site_name: OPIL
site_url: https://opil-documentation.readthedocs.org
repo_url: https://github.com/opil/documentation.git
site_description: OPIL Documentation
site_author: OPIL Team
docs_dir: docs
site_dir: html

markdown_extensions:
    - toc:
        baselevel: 3
    - fenced_code

use_directory_urls: false

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
nav:
    - Home: index.md
    - Getting Started: 
        - Introduction to OPIL: start/index.md
        - Deployment: start/deployment.md
    - Showcases:
        - Introduction: showcases/index.md 
        - Chemi: showcases/chemi.md
        - Engino: showcases/engino.md
        - Chemi: showcases/muraplast.md
    - Administrator's Guide: 
        - Introduction: admin/index.md
        - Installation:
            - OPIL Networking: admin/OPIL/opil_networking.md
            - OPIL Server: admin/OPIL/opil_server.md
            - OPIL Modules:
                - Task Planner: 
                    - Installation: admin/TP/opil_server_tp_install.md
                    - Getting started: admin/TP/opil_server_tp_gettingStarted.md
                    - Deinstallation: admin/TP/opil_server_tp_deinstall.md
                    - Upgrades: admin/TP/opil_server_upgrade.md
                    - Deprecated: admin/TP/opil_server_tp_deprecated.md 
                - Human Machine Interaction: 
                    - Installation: admin/HMI/opil_server_hmi.md
                    - Getting started: admin/HMI/opil_server_hmi_gettingStarted.md
                    - Deinstallation: admin/HMI/opil_server_hmi_deinstall.md
                    - Upgrades: admin/HMI/opil_server_hmi_upgrades.md
                    - Deprecated: admin/HMI/opil_server_hmi_deprecated.md
                - Sensing and Perception: admin/SP/opil_server_sp.md
                    - Installation: admin/SP/opil_server_sp_install.md
                    - Getting started: admin/SP/opil_server_sp_gettingStarted.md
                    - Deinstallation: admin/SP/opil_server_sp_deinstall.md
                    - Upgrades: admin/SP/opil_server_sp_upgrades.md
                    - Deprecated: admin/SP/opil_server_sp_deprecated.md                
            - IoT Device Nodes:
                - Introduction: admin/opil_iot.md
                - RAN: admin/RAN/opil_iot_ran.md
                - SAN: admin/SAN/opil_iot_san.md
                - HAN: admin/HAN/opil_iot_han.md
            - IoT Visual Components Nodes:
                - Introduction: admin/opil_vc.md
                - RAN VC: admin/RANVC/opil_vc_ran.md
                - SAN VC: admin/SANVC/opil_vc_sanvc.md
                - SAN VC Actuator: admin/SANVCACT/opil_vc_sanvcact.md
        - Modules Description:
            - Introduction: admin/OPIL/opil_conf_intro.md
            - IoT Devices Nodes:
                - Introduction:
                - RAN:
                - SAN:
                - HAN:
            - IoT Visual Components Nodes:
                - VC RAN:
                - VC SAN:
                - VC SAN Actuator:
            - Functional Modules:                              
                - Task Planner:
                    - Introduction: develop/opil_config_tp_intro.mkdocs
                    - Business Process Optimization:  develop/opil_config_tp_bpo.md
                    - Motion Path Planning:  develop/opil_config_tp_mpp.md
                    - Task Supervisor:   develop/opil_config_tp_tasksupervisor.md
                - Sesing & Perception:
        - Human Machine Interaction:
            -   Introduction: admin/opil_config_HMI_intro.md        
    - Developer's Guide:
        - Introduction: develop/index.md
        - Technology Guidelines: develop/technology_guidelines.md
        - Programming Guidelines: develop/technology_programming.md 
        - API Documentation:
            - Module:
                - Task Planner:
                    - Introduction: develop/opil_tp_API_intro
                    - API: develop/tp_api.md
                    - Interfaces: develop/opil_tp_interfaces.md
                - Human Machine Interaction: develop/opil_api_hmi.md
                - Sensing & Perception: develop/opil_api_sp.md
            - Nodes:
                - Robot Agent Node (RAN): develop/opil_api_ran.md
                - Sensor Agent Node (SAN): develop/opil_api_san.md
                - Human Agent Node (HAN):  
            - Examples: develop/examples.md
theme: readthedocs
plugins:
    - search
